# .streamlit/secrets.toml

[db_credentials]
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "2Dv1chx9hoFRkxE.analytics_user"
password = "your_database_password_here" # Replace with your actual password
db = "airplugprod"

[google_api_key]
api_key = "your_google_api_key_here" # Replace with your actual Gemini API key

[google_drive]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"
